'use client';

import { useMemo, useState } from 'react';

type Intel={score:number;status:string;intelligence_map:Array<{label:string;value:string;status:string}>;action_queue:Array<{action:string;priority:string;impact:string}>;contributor_lanes:Array<{lane:string;mission:string}>};
const starter='Need a founding operations lead who owns support, reporting, vendor follow-up, and the daily execution rhythm.';
const capabilities=[['Role mission','Turn a vague hiring need into a clear reason the role exists.'],['Outcome scorecard','Define measurable proof of fit for the first 90 days.'],['Decision rights','Make ownership, autonomy, and escalation boundaries explicit.'],['Interview signals','Convert outcomes into evidence-based hiring questions.']] as const;
function fallback(subject:string):Intel{const score=Math.min(96,61+(subject.length%29));return{score,status:score>84?'strong':score>72?'ready':'needs review',intelligence_map:capabilities.map(([label,value])=>({label,value,status:'defined'})),action_queue:[{action:'Own the weekly operating rhythm',priority:'Core',impact:'Publish priorities, surface blockers, and close follow-ups across the team.'},{action:'Reduce founder coordination load',priority:'Outcome',impact:'Move recurring vendor, support, and reporting decisions into a documented system.'},{action:'Build a measurable 90-day baseline',priority:'Metric',impact:'Define response times, reporting cadence, and operating-quality targets.'}],contributor_lanes:[]};}

export default function Home(){
 const [subject,setSubject]=useState(starter);const [intel,setIntel]=useState<Intel>(()=>fallback(starter));const [loading,setLoading]=useState(false);const tone=useMemo(()=>intel.score>=86?'strong':intel.score>=72?'ready':'review',[intel.score]);
 async function run(){setLoading(true);try{const response=await fetch('/api/intelligence',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({input:subject})});setIntel(await response.json());}finally{setLoading(false);}}
 return <main>
  <header className="topbar"><a className="logo" href="#top"><span>RF</span><b>RoleForge</b></a><nav aria-label="Primary navigation"><a href="#builder">Builder</a><a href="#blueprint">Blueprint</a><a href="#scorecard">Scorecard</a></nav><a className="nav-cta" href="#builder">Forge a role <span>↗</span></a></header>
  <section className="hero" id="top"><div className="hero-copy"><p className="kicker">ORG DESIGN SYSTEM <i>v1.0</i></p><h1>Build the role <em>before</em> you hire the person.</h1><p className="subhead">Turn a messy hiring need into a crisp mission, decision rights, 90-day outcomes, and an interview-ready scorecard.</p><div className="hero-buttons"><a className="btn primary" href="#builder">Create role blueprint <span>→</span></a><a className="btn ghost" href="#blueprint">View example</a></div><div className="proof"><span><b>01</b> Clear ownership</span><span><b>02</b> Measurable outcomes</span><span><b>03</b> Better interviews</span></div></div>
   <div className="forge-card" id="builder"><div className="forge-bar"><span>ROLEFORGE / NEW BLUEPRINT</span><span className="live">● READY</span></div><div className="forge-title"><div><small>ROLE INPUT</small><h2>What does your team need?</h2></div><div className={`clarity ${tone}`}><span>CLARITY</span><strong>{intel.score}</strong><small>/100</small></div></div><label className="sr-only" htmlFor="role-input">Describe the role your team needs</label><textarea id="role-input" value={subject} onChange={e=>setSubject(e.target.value)}/><div className="suggestions"><span>Try:</span><button onClick={()=>setSubject('First product marketer to own positioning, launches, and pipeline experiments')}>First product marketer</button><button onClick={()=>setSubject('Customer success lead for onboarding, retention, and expansion')}>Customer success lead</button></div><button className="forge-button" onClick={run} disabled={loading}>{loading?'Mapping ownership…':'Forge role blueprint'}<span>⌘ ↵</span></button><div className="forge-status"><span><i/> Mission mapped</span><span><i/> Outcomes defined</span><span><i/> Boundaries checked</span></div></div>
  </section>
  <section className="blueprint" id="blueprint"><div className="section-intro"><p className="kicker">01 / ROLE BLUEPRINT</p><h2>A role people can actually succeed in.</h2><p>RoleForge creates an operating contract for the role—not a wishlist disguised as a job description.</p></div><div className="blueprint-grid"><aside><p className="rail-label">BLUEPRINT INDEX</p>{intel.intelligence_map.map((item,index)=><a href={`#panel-${index}`} key={item.label} className={index===0?'active':''}><span>0{index+1}</span><div><b>{item.label}</b><small>{item.status}</small></div></a>)}</aside><article className="mission-panel" id="panel-0"><div className="panel-top"><span className="tag">ROLE MISSION</span><span className="version">DRAFT 01</span></div><blockquote>Own the operating rhythm that turns founder priorities into consistent team execution.</blockquote><div className="boundaries"><div><small>OWNS</small><p>Support operations, vendor follow-up, weekly reporting, and execution cadence.</p></div><div><small>DOES NOT OWN</small><p>Company strategy, final budget approval, or specialist functional decisions.</p></div></div><div className="collab-row"><span>WORKS WITH</span><b>Founder</b><b>Product</b><b>Finance</b><b>Vendors</b></div></article></div></section>
  <section className="outcomes" id="scorecard"><div className="section-intro compact"><p className="kicker">02 / SUCCESS SCORECARD</p><h2>Define success before day one.</h2></div><div className="outcome-grid">{intel.action_queue.map((item,index)=><article key={item.action}><div className="outcome-top"><span>0{index+1}</span><span className={`tag tag-${item.priority.toLowerCase()}`}>{item.priority}</span></div><h3>{item.action}</h3><p>{item.impact}</p><div className="meter"><i style={{width:`${72+index*8}%`}}/></div><small>OUTCOME DEFINITION</small></article>)}</div></section>
  <section className="process"><div className="section-intro compact"><p className="kicker">03 / FROM NEED TO HIRE</p><h2>One brief. A clearer hiring loop.</h2></div><ol><li><span>01</span><div><h3>Describe the gap</h3><p>Start with the work that is falling through—not a recycled job title.</p></div></li><li><span>02</span><div><h3>Shape ownership</h3><p>Separate responsibilities, decisions, collaboration, and success measures.</p></div></li><li><span>03</span><div><h3>Interview for evidence</h3><p>Use the scorecard to test for proof instead of relying on intuition.</p></div></li></ol><a className="final-cta" href="#builder">Forge your next role <span>→</span></a></section>
  <footer><div className="logo"><span>RF</span><b>RoleForge</b></div><p>Clear roles. Stronger teams.</p><a href="#top">Back to top ↑</a></footer>
 </main>}
